///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace pbs_web_automation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PBS_Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7b5e8d22-7d7f-4c0d-a9a0-8f6667bebe64")]
    public partial class PBS_Repository : RepoGenBaseFolder
    {
        static PBS_Repository instance = new PBS_Repository();
        PBS_RepositoryFolders.Pbs_webSiteAppFolder _pbs_website;
        PBS_RepositoryFolders.Pbs_shopSiteAppFolder _pbs_shopsite;

        /// <summary>
        /// Gets the singleton class instance representing the PBS_Repository element repository.
        /// </summary>
        [RepositoryFolder("7b5e8d22-7d7f-4c0d-a9a0-8f6667bebe64")]
        public static PBS_Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PBS_Repository() 
            : base("PBS_Repository", "/", null, 0, false, "7b5e8d22-7d7f-4c0d-a9a0-8f6667bebe64", ".\\RepositoryImages\\PBS_Repository7b5e8d22.rximgres")
        {
            _pbs_website = new PBS_RepositoryFolders.Pbs_webSiteAppFolder(this);
            _pbs_shopsite = new PBS_RepositoryFolders.Pbs_shopSiteAppFolder(this);
        }

#region Variables

        string _batterie1 = "";

        /// <summary>
        /// Gets or sets the value of variable batterie1.
        /// </summary>
        [TestVariable("a3bcdbf1-5898-46d4-9a71-86d538f1f52b")]
        public string batterie1
        {
            get { return _batterie1; }
            set { _batterie1 = value; }
        }

        string _varProduct1 = "";

        /// <summary>
        /// Gets or sets the value of variable varProduct1.
        /// </summary>
        [TestVariable("b070db51-97f6-4cdd-a8b6-ca691242477b")]
        public string varProduct1
        {
            get { return _varProduct1; }
            set { _varProduct1 = value; }
        }

        string _varProduct2 = "";

        /// <summary>
        /// Gets or sets the value of variable varProduct2.
        /// </summary>
        [TestVariable("d9e2e6aa-e4d2-4158-9d8f-01b927f841c1")]
        public string varProduct2
        {
            get { return _varProduct2; }
            set { _varProduct2 = value; }
        }

        string _varChosenProduct1 = "";

        /// <summary>
        /// Gets or sets the value of variable varChosenProduct1.
        /// </summary>
        [TestVariable("0b84ec6a-3eed-4221-90ef-08943857ff01")]
        public string varChosenProduct1
        {
            get { return _varChosenProduct1; }
            set { _varChosenProduct1 = value; }
        }

        string _varChosenProduct2 = "";

        /// <summary>
        /// Gets or sets the value of variable varChosenProduct2.
        /// </summary>
        [TestVariable("efc2dd9e-6015-4679-8e6c-35d6c727ef50")]
        public string varChosenProduct2
        {
            get { return _varChosenProduct2; }
            set { _varChosenProduct2 = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7b5e8d22-7d7f-4c0d-a9a0-8f6667bebe64")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The pbs_webSite folder.
        /// </summary>
        [RepositoryFolder("5ad8291b-b4f3-4cac-9859-481ccf7a640a")]
        public virtual PBS_RepositoryFolders.Pbs_webSiteAppFolder pbs_webSite
        {
            get { return _pbs_website; }
        }

        /// <summary>
        /// The pbs_shopSite folder.
        /// </summary>
        [RepositoryFolder("5d0c5407-5174-46d5-8a07-0ceee31a019a")]
        public virtual PBS_RepositoryFolders.Pbs_shopSiteAppFolder pbs_shopSite
        {
            get { return _pbs_shopsite; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PBS_RepositoryFolders
    {
        /// <summary>
        /// The Pbs_webSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("5ad8291b-b4f3-4cac-9859-481ccf7a640a")]
        public partial class Pbs_webSiteAppFolder : RepoGenBaseFolder
        {
            PBS_RepositoryFolders.HomePageFolder _homepage;
            PBS_RepositoryFolders.NavbarFolder _navbar;
            PBS_RepositoryFolders.PartnerBereichPageFolder _partnerbereichpage;

            /// <summary>
            /// Creates a new pbs_webSite  folder.
            /// </summary>
            public Pbs_webSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("pbs_webSite", "/dom[@domain='www.pbs-austria.at']", parentFolder, 30000, null, false, "5ad8291b-b4f3-4cac-9859-481ccf7a640a", "")
            {
                _homepage = new PBS_RepositoryFolders.HomePageFolder(this);
                _navbar = new PBS_RepositoryFolders.NavbarFolder(this);
                _partnerbereichpage = new PBS_RepositoryFolders.PartnerBereichPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5ad8291b-b4f3-4cac-9859-481ccf7a640a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5ad8291b-b4f3-4cac-9859-481ccf7a640a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("c25af088-801d-4929-b7ce-94f71e774d02")]
            public virtual PBS_RepositoryFolders.HomePageFolder HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The Navbar folder.
            /// </summary>
            [RepositoryFolder("293be9cb-6058-436f-8aa1-97f47cca557a")]
            public virtual PBS_RepositoryFolders.NavbarFolder Navbar
            {
                get { return _navbar; }
            }

            /// <summary>
            /// The PartnerBereichPage folder.
            /// </summary>
            [RepositoryFolder("6397d9cb-9196-407e-9874-fbd641e3e292")]
            public virtual PBS_RepositoryFolders.PartnerBereichPageFolder PartnerBereichPage
            {
                get { return _partnerbereichpage; }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("c25af088-801d-4929-b7ce-94f71e774d02")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoInfo;
            RepoItemInfo _unternehmenInfo;
            RepoItemInfo _sortimentInfo;
            RepoItemInfo _dienstleistungenInfo;
            RepoItemInfo _logistikInfo;
            RepoItemInfo _kontaktInfo;
            RepoItemInfo _fernwartungInfo;
            RepoItemInfo _partnerbereichInfo;
            RepoItemInfo _carouselInfo;
            RepoItemInfo _onlineshopInfo;
            RepoItemInfo _pbs_aktuellInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "c25af088-801d-4929-b7ce-94f71e774d02", "")
            {
                _logoInfo = new RepoItemInfo(this, "Logo", ".//img[@class='mobile' and @tagname='img']", "element", 30000, null, "75f5e518-9a5a-4763-a5f5-a6f15ff07e35");
                _unternehmenInfo = new RepoItemInfo(this, "Unternehmen", ".//span[@innertext='Unternehmen']", "element", 30000, null, "e68b2fe6-1301-46ed-86bd-9915813d8fa2");
                _sortimentInfo = new RepoItemInfo(this, "Sortiment", ".//span[@innertext='Sortiment']", "element", 30000, null, "d377040f-4717-4e38-bf7e-298f0fc3ff2d");
                _dienstleistungenInfo = new RepoItemInfo(this, "Dienstleistungen", ".//span[@innertext='Dienstleistungen']", "element", 30000, null, "652812a9-6e6c-4d0c-9396-d93d3b4ae027");
                _logistikInfo = new RepoItemInfo(this, "Logistik", ".//span[@innertext='Logistik']", "element", 30000, null, "1fbb958c-1e86-4776-ba2e-633c3f6ebd84");
                _kontaktInfo = new RepoItemInfo(this, "Kontakt", ".//span[@innertext='Kontakt']", "element", 30000, null, "3665edbe-b556-446c-840b-bf6d3912ae61");
                _fernwartungInfo = new RepoItemInfo(this, "Fernwartung", ".//span[@innertext='Fernwartung']", "element", 30000, null, "c228e6c2-b05c-40e2-a955-080d7d1fc7df");
                _partnerbereichInfo = new RepoItemInfo(this, "Partnerbereich", ".//span[@innertext='Partnerbereich']", "element", 30000, null, "34cbb1ce-0615-4cc8-9875-982d658172a4");
                _carouselInfo = new RepoItemInfo(this, "Carousel", ".//tag[@tagname='rs-slides']/tag[2]/tag[@tagname='rs-layer-wrap']/tag[@tagname='rs-layer']", "element", 30000, null, "89df16ce-a875-4ca0-827b-0e9817dc3a21");
                _onlineshopInfo = new RepoItemInfo(this, "OnlineShop", ".//a[@innertext='Online Shop']", "element", 30000, null, "6443c714-c3e2-4f08-b68a-7721093b325f");
                _pbs_aktuellInfo = new RepoItemInfo(this, "PBS_Aktuell", ".//a[@innertext='PBS Aktuell – monatliche Sortiment-Information']", "element", 30000, null, "831a77b4-3b69-4f1a-9333-1dcaeeaa52e9");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c25af088-801d-4929-b7ce-94f71e774d02")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logo item.
            /// </summary>
            [RepositoryItem("75f5e518-9a5a-4763-a5f5-a6f15ff07e35")]
            public virtual Ranorex.ImgTag Logo
            {
                get
                {
                    return _logoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Logo item info.
            /// </summary>
            [RepositoryItemInfo("75f5e518-9a5a-4763-a5f5-a6f15ff07e35")]
            public virtual RepoItemInfo LogoInfo
            {
                get
                {
                    return _logoInfo;
                }
            }

            /// <summary>
            /// The Unternehmen item.
            /// </summary>
            [RepositoryItem("e68b2fe6-1301-46ed-86bd-9915813d8fa2")]
            public virtual Ranorex.SpanTag Unternehmen
            {
                get
                {
                    return _unternehmenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Unternehmen item info.
            /// </summary>
            [RepositoryItemInfo("e68b2fe6-1301-46ed-86bd-9915813d8fa2")]
            public virtual RepoItemInfo UnternehmenInfo
            {
                get
                {
                    return _unternehmenInfo;
                }
            }

            /// <summary>
            /// The Sortiment item.
            /// </summary>
            [RepositoryItem("d377040f-4717-4e38-bf7e-298f0fc3ff2d")]
            public virtual Ranorex.SpanTag Sortiment
            {
                get
                {
                    return _sortimentInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Sortiment item info.
            /// </summary>
            [RepositoryItemInfo("d377040f-4717-4e38-bf7e-298f0fc3ff2d")]
            public virtual RepoItemInfo SortimentInfo
            {
                get
                {
                    return _sortimentInfo;
                }
            }

            /// <summary>
            /// The Dienstleistungen item.
            /// </summary>
            [RepositoryItem("652812a9-6e6c-4d0c-9396-d93d3b4ae027")]
            public virtual Ranorex.SpanTag Dienstleistungen
            {
                get
                {
                    return _dienstleistungenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Dienstleistungen item info.
            /// </summary>
            [RepositoryItemInfo("652812a9-6e6c-4d0c-9396-d93d3b4ae027")]
            public virtual RepoItemInfo DienstleistungenInfo
            {
                get
                {
                    return _dienstleistungenInfo;
                }
            }

            /// <summary>
            /// The Logistik item.
            /// </summary>
            [RepositoryItem("1fbb958c-1e86-4776-ba2e-633c3f6ebd84")]
            public virtual Ranorex.SpanTag Logistik
            {
                get
                {
                    return _logistikInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Logistik item info.
            /// </summary>
            [RepositoryItemInfo("1fbb958c-1e86-4776-ba2e-633c3f6ebd84")]
            public virtual RepoItemInfo LogistikInfo
            {
                get
                {
                    return _logistikInfo;
                }
            }

            /// <summary>
            /// The Kontakt item.
            /// </summary>
            [RepositoryItem("3665edbe-b556-446c-840b-bf6d3912ae61")]
            public virtual Ranorex.SpanTag Kontakt
            {
                get
                {
                    return _kontaktInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Kontakt item info.
            /// </summary>
            [RepositoryItemInfo("3665edbe-b556-446c-840b-bf6d3912ae61")]
            public virtual RepoItemInfo KontaktInfo
            {
                get
                {
                    return _kontaktInfo;
                }
            }

            /// <summary>
            /// The Fernwartung item.
            /// </summary>
            [RepositoryItem("c228e6c2-b05c-40e2-a955-080d7d1fc7df")]
            public virtual Ranorex.SpanTag Fernwartung
            {
                get
                {
                    return _fernwartungInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Fernwartung item info.
            /// </summary>
            [RepositoryItemInfo("c228e6c2-b05c-40e2-a955-080d7d1fc7df")]
            public virtual RepoItemInfo FernwartungInfo
            {
                get
                {
                    return _fernwartungInfo;
                }
            }

            /// <summary>
            /// The Partnerbereich item.
            /// </summary>
            [RepositoryItem("34cbb1ce-0615-4cc8-9875-982d658172a4")]
            public virtual Ranorex.SpanTag Partnerbereich
            {
                get
                {
                    return _partnerbereichInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Partnerbereich item info.
            /// </summary>
            [RepositoryItemInfo("34cbb1ce-0615-4cc8-9875-982d658172a4")]
            public virtual RepoItemInfo PartnerbereichInfo
            {
                get
                {
                    return _partnerbereichInfo;
                }
            }

            /// <summary>
            /// The Carousel item.
            /// </summary>
            [RepositoryItem("89df16ce-a875-4ca0-827b-0e9817dc3a21")]
            public virtual Ranorex.WebElement Carousel
            {
                get
                {
                    return _carouselInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Carousel item info.
            /// </summary>
            [RepositoryItemInfo("89df16ce-a875-4ca0-827b-0e9817dc3a21")]
            public virtual RepoItemInfo CarouselInfo
            {
                get
                {
                    return _carouselInfo;
                }
            }

            /// <summary>
            /// The OnlineShop item.
            /// </summary>
            [RepositoryItem("6443c714-c3e2-4f08-b68a-7721093b325f")]
            public virtual Ranorex.ATag OnlineShop
            {
                get
                {
                    return _onlineshopInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OnlineShop item info.
            /// </summary>
            [RepositoryItemInfo("6443c714-c3e2-4f08-b68a-7721093b325f")]
            public virtual RepoItemInfo OnlineShopInfo
            {
                get
                {
                    return _onlineshopInfo;
                }
            }

            /// <summary>
            /// The PBS_Aktuell item.
            /// </summary>
            [RepositoryItem("831a77b4-3b69-4f1a-9333-1dcaeeaa52e9")]
            public virtual Ranorex.ATag PBS_Aktuell
            {
                get
                {
                    return _pbs_aktuellInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PBS_Aktuell item info.
            /// </summary>
            [RepositoryItemInfo("831a77b4-3b69-4f1a-9333-1dcaeeaa52e9")]
            public virtual RepoItemInfo PBS_AktuellInfo
            {
                get
                {
                    return _pbs_aktuellInfo;
                }
            }
        }

        /// <summary>
        /// The NavbarFolder folder.
        /// </summary>
        [RepositoryFolder("293be9cb-6058-436f-8aa1-97f47cca557a")]
        public partial class NavbarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _unternehmensgruppeInfo;
            RepoItemInfo _uberunsInfo;
            RepoItemInfo _geschichteInfo;
            RepoItemInfo _karriereInfo;
            RepoItemInfo _dasteamInfo;
            RepoItemInfo _unserproduktangebotInfo;
            RepoItemInfo _q_connectInfo;
            RepoItemInfo _donauInfo;
            RepoItemInfo _e_committedInfo;
            RepoItemInfo _persoenlichebetreuungInfo;
            RepoItemInfo _marketing_serviceInfo;
            RepoItemInfo _weiteres_know_howInfo;
            RepoItemInfo _cipscub_systempartnerschaftInfo;
            RepoItemInfo _logistikzentrumInfo;
            RepoItemInfo _it___prozesseInfo;
            RepoItemInfo _kleinteile_lagerInfo;
            RepoItemInfo _grossteile_lagerInfo;
            RepoItemInfo _ansprechpartnerInfo;
            RepoItemInfo _anfahrtsplanInfo;
            RepoItemInfo _kontaktdatenInfo;

            /// <summary>
            /// Creates a new Navbar  folder.
            /// </summary>
            public NavbarFolder(RepoGenBaseFolder parentFolder) :
                    base("Navbar", "", parentFolder, 0, null, false, "293be9cb-6058-436f-8aa1-97f47cca557a", "")
            {
                _unternehmensgruppeInfo = new RepoItemInfo(this, "Unternehmensgruppe", ".//span[@innertext='Unternehmensgruppe']", "element", 30000, null, "16b25cf6-a4ae-4c3b-92ae-10b7bd674805");
                _uberunsInfo = new RepoItemInfo(this, "UberUns", ".//span[@innertext='Über uns']", "element", 30000, null, "35176ad7-05ef-485b-a5af-4a26466a8005");
                _geschichteInfo = new RepoItemInfo(this, "Geschichte", ".//span[@innertext='Geschichte']", "element", 30000, null, "6b536416-6f91-41e0-9cd3-b63f13145f68");
                _karriereInfo = new RepoItemInfo(this, "Karriere", ".//span[@innertext='Karriere']", "element", 30000, null, "04c81067-5f9b-4235-8d88-c1adc5e9ad42");
                _dasteamInfo = new RepoItemInfo(this, "DasTeam", ".//span[@innertext='Das Team']", "element", 30000, null, "05cbccd8-19e5-4623-b1e3-4c8015eaaf56");
                _unserproduktangebotInfo = new RepoItemInfo(this, "UnserProduktangebot", ".//span[@innertext='Unser Produktangebot']", "element", 30000, null, "3132008a-176d-486c-8731-a75b351aa4f0");
                _q_connectInfo = new RepoItemInfo(this, "Q_Connect", ".//span[@innertext='Q-Connect']", "element", 30000, null, "2694fadb-c3e7-4780-a458-e7e7061440db");
                _donauInfo = new RepoItemInfo(this, "Donau", ".//span[@innertext='Donau']", "element", 30000, null, "4360738e-6ca6-42d1-991c-f67e99965494");
                _e_committedInfo = new RepoItemInfo(this, "E_Committed", ".//span[@innertext='E-Committed']", "element", 30000, null, "76214bc2-e0b9-4c03-a203-0c36dcce6def");
                _persoenlichebetreuungInfo = new RepoItemInfo(this, "PersoenlicheBetreuung", ".//span[@innertext='Persönliche Betreuung']", "element", 30000, null, "96fd0c2e-76fd-4559-adec-4f92c203864a");
                _marketing_serviceInfo = new RepoItemInfo(this, "Marketing_Service", ".//span[@innertext='Marketing-Service']", "element", 30000, null, "7c517211-222b-4609-806a-8fbd7195b4ae");
                _weiteres_know_howInfo = new RepoItemInfo(this, "Weiteres_Know_how", ".//span[@innertext='Weiteres Know-how']", "element", 30000, null, "01b96586-8e2a-479f-ba2c-44c654bf2e59");
                _cipscub_systempartnerschaftInfo = new RepoItemInfo(this, "CIPSCub_Systempartnerschaft", ".//span[@innertext='CIPS³-Systempartnerschaft']", "element", 30000, null, "236db85d-6bdd-4e64-9487-c5efbccb79bf");
                _logistikzentrumInfo = new RepoItemInfo(this, "Logistikzentrum", ".//span[@innertext='Logistikzentrum']", "element", 30000, null, "7c3f508a-7a0d-424a-907c-a3a215190a2a");
                _it___prozesseInfo = new RepoItemInfo(this, "IT___PROZESSE", ".//span[@innertext='IT / PROZESSE']", "element", 30000, null, "a4e8e09e-a382-48b9-ab9c-90bab120be64");
                _kleinteile_lagerInfo = new RepoItemInfo(this, "Kleinteile_lager", ".//span[@innertext='Kleinteile-lager']", "element", 30000, null, "2d547e15-0327-462e-8765-583634b624e0");
                _grossteile_lagerInfo = new RepoItemInfo(this, "grossteile_lager", ".//span[@innertext='grossteile-lager']", "element", 30000, null, "e8c65586-519a-4be7-95a7-4fa92d0cf2c1");
                _ansprechpartnerInfo = new RepoItemInfo(this, "Ansprechpartner", ".//span[@innertext='Ansprechpartner']", "element", 30000, null, "1ad16f6b-2591-46a7-8c5f-77f1458c5ab6");
                _anfahrtsplanInfo = new RepoItemInfo(this, "Anfahrtsplan", ".//span[@innertext='Anfahrtsplan']", "element", 30000, null, "c3213a13-836b-4ae6-a38d-e5af041caeec");
                _kontaktdatenInfo = new RepoItemInfo(this, "Kontaktdaten", ".//span[@innertext='Kontaktdaten']", "element", 30000, null, "22b344e1-6d44-4634-b093-636330ef157a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("293be9cb-6058-436f-8aa1-97f47cca557a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Unternehmensgruppe item.
            /// </summary>
            [RepositoryItem("16b25cf6-a4ae-4c3b-92ae-10b7bd674805")]
            public virtual Ranorex.SpanTag Unternehmensgruppe
            {
                get
                {
                    return _unternehmensgruppeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Unternehmensgruppe item info.
            /// </summary>
            [RepositoryItemInfo("16b25cf6-a4ae-4c3b-92ae-10b7bd674805")]
            public virtual RepoItemInfo UnternehmensgruppeInfo
            {
                get
                {
                    return _unternehmensgruppeInfo;
                }
            }

            /// <summary>
            /// The UberUns item.
            /// </summary>
            [RepositoryItem("35176ad7-05ef-485b-a5af-4a26466a8005")]
            public virtual Ranorex.SpanTag UberUns
            {
                get
                {
                    return _uberunsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UberUns item info.
            /// </summary>
            [RepositoryItemInfo("35176ad7-05ef-485b-a5af-4a26466a8005")]
            public virtual RepoItemInfo UberUnsInfo
            {
                get
                {
                    return _uberunsInfo;
                }
            }

            /// <summary>
            /// The Geschichte item.
            /// </summary>
            [RepositoryItem("6b536416-6f91-41e0-9cd3-b63f13145f68")]
            public virtual Ranorex.SpanTag Geschichte
            {
                get
                {
                    return _geschichteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Geschichte item info.
            /// </summary>
            [RepositoryItemInfo("6b536416-6f91-41e0-9cd3-b63f13145f68")]
            public virtual RepoItemInfo GeschichteInfo
            {
                get
                {
                    return _geschichteInfo;
                }
            }

            /// <summary>
            /// The Karriere item.
            /// </summary>
            [RepositoryItem("04c81067-5f9b-4235-8d88-c1adc5e9ad42")]
            public virtual Ranorex.SpanTag Karriere
            {
                get
                {
                    return _karriereInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Karriere item info.
            /// </summary>
            [RepositoryItemInfo("04c81067-5f9b-4235-8d88-c1adc5e9ad42")]
            public virtual RepoItemInfo KarriereInfo
            {
                get
                {
                    return _karriereInfo;
                }
            }

            /// <summary>
            /// The DasTeam item.
            /// </summary>
            [RepositoryItem("05cbccd8-19e5-4623-b1e3-4c8015eaaf56")]
            public virtual Ranorex.SpanTag DasTeam
            {
                get
                {
                    return _dasteamInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DasTeam item info.
            /// </summary>
            [RepositoryItemInfo("05cbccd8-19e5-4623-b1e3-4c8015eaaf56")]
            public virtual RepoItemInfo DasTeamInfo
            {
                get
                {
                    return _dasteamInfo;
                }
            }

            /// <summary>
            /// The UnserProduktangebot item.
            /// </summary>
            [RepositoryItem("3132008a-176d-486c-8731-a75b351aa4f0")]
            public virtual Ranorex.SpanTag UnserProduktangebot
            {
                get
                {
                    return _unserproduktangebotInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The UnserProduktangebot item info.
            /// </summary>
            [RepositoryItemInfo("3132008a-176d-486c-8731-a75b351aa4f0")]
            public virtual RepoItemInfo UnserProduktangebotInfo
            {
                get
                {
                    return _unserproduktangebotInfo;
                }
            }

            /// <summary>
            /// The Q_Connect item.
            /// </summary>
            [RepositoryItem("2694fadb-c3e7-4780-a458-e7e7061440db")]
            public virtual Ranorex.SpanTag Q_Connect
            {
                get
                {
                    return _q_connectInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Q_Connect item info.
            /// </summary>
            [RepositoryItemInfo("2694fadb-c3e7-4780-a458-e7e7061440db")]
            public virtual RepoItemInfo Q_ConnectInfo
            {
                get
                {
                    return _q_connectInfo;
                }
            }

            /// <summary>
            /// The Donau item.
            /// </summary>
            [RepositoryItem("4360738e-6ca6-42d1-991c-f67e99965494")]
            public virtual Ranorex.SpanTag Donau
            {
                get
                {
                    return _donauInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Donau item info.
            /// </summary>
            [RepositoryItemInfo("4360738e-6ca6-42d1-991c-f67e99965494")]
            public virtual RepoItemInfo DonauInfo
            {
                get
                {
                    return _donauInfo;
                }
            }

            /// <summary>
            /// The E_Committed item.
            /// </summary>
            [RepositoryItem("76214bc2-e0b9-4c03-a203-0c36dcce6def")]
            public virtual Ranorex.SpanTag E_Committed
            {
                get
                {
                    return _e_committedInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The E_Committed item info.
            /// </summary>
            [RepositoryItemInfo("76214bc2-e0b9-4c03-a203-0c36dcce6def")]
            public virtual RepoItemInfo E_CommittedInfo
            {
                get
                {
                    return _e_committedInfo;
                }
            }

            /// <summary>
            /// The PersoenlicheBetreuung item.
            /// </summary>
            [RepositoryItem("96fd0c2e-76fd-4559-adec-4f92c203864a")]
            public virtual Ranorex.SpanTag PersoenlicheBetreuung
            {
                get
                {
                    return _persoenlichebetreuungInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PersoenlicheBetreuung item info.
            /// </summary>
            [RepositoryItemInfo("96fd0c2e-76fd-4559-adec-4f92c203864a")]
            public virtual RepoItemInfo PersoenlicheBetreuungInfo
            {
                get
                {
                    return _persoenlichebetreuungInfo;
                }
            }

            /// <summary>
            /// The Marketing_Service item.
            /// </summary>
            [RepositoryItem("7c517211-222b-4609-806a-8fbd7195b4ae")]
            public virtual Ranorex.SpanTag Marketing_Service
            {
                get
                {
                    return _marketing_serviceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Marketing_Service item info.
            /// </summary>
            [RepositoryItemInfo("7c517211-222b-4609-806a-8fbd7195b4ae")]
            public virtual RepoItemInfo Marketing_ServiceInfo
            {
                get
                {
                    return _marketing_serviceInfo;
                }
            }

            /// <summary>
            /// The Weiteres_Know_how item.
            /// </summary>
            [RepositoryItem("01b96586-8e2a-479f-ba2c-44c654bf2e59")]
            public virtual Ranorex.SpanTag Weiteres_Know_how
            {
                get
                {
                    return _weiteres_know_howInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Weiteres_Know_how item info.
            /// </summary>
            [RepositoryItemInfo("01b96586-8e2a-479f-ba2c-44c654bf2e59")]
            public virtual RepoItemInfo Weiteres_Know_howInfo
            {
                get
                {
                    return _weiteres_know_howInfo;
                }
            }

            /// <summary>
            /// The CIPSCub_Systempartnerschaft item.
            /// </summary>
            [RepositoryItem("236db85d-6bdd-4e64-9487-c5efbccb79bf")]
            public virtual Ranorex.SpanTag CIPSCub_Systempartnerschaft
            {
                get
                {
                    return _cipscub_systempartnerschaftInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CIPSCub_Systempartnerschaft item info.
            /// </summary>
            [RepositoryItemInfo("236db85d-6bdd-4e64-9487-c5efbccb79bf")]
            public virtual RepoItemInfo CIPSCub_SystempartnerschaftInfo
            {
                get
                {
                    return _cipscub_systempartnerschaftInfo;
                }
            }

            /// <summary>
            /// The Logistikzentrum item.
            /// </summary>
            [RepositoryItem("7c3f508a-7a0d-424a-907c-a3a215190a2a")]
            public virtual Ranorex.SpanTag Logistikzentrum
            {
                get
                {
                    return _logistikzentrumInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Logistikzentrum item info.
            /// </summary>
            [RepositoryItemInfo("7c3f508a-7a0d-424a-907c-a3a215190a2a")]
            public virtual RepoItemInfo LogistikzentrumInfo
            {
                get
                {
                    return _logistikzentrumInfo;
                }
            }

            /// <summary>
            /// The IT___PROZESSE item.
            /// </summary>
            [RepositoryItem("a4e8e09e-a382-48b9-ab9c-90bab120be64")]
            public virtual Ranorex.SpanTag IT___PROZESSE
            {
                get
                {
                    return _it___prozesseInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The IT___PROZESSE item info.
            /// </summary>
            [RepositoryItemInfo("a4e8e09e-a382-48b9-ab9c-90bab120be64")]
            public virtual RepoItemInfo IT___PROZESSEInfo
            {
                get
                {
                    return _it___prozesseInfo;
                }
            }

            /// <summary>
            /// The Kleinteile_lager item.
            /// </summary>
            [RepositoryItem("2d547e15-0327-462e-8765-583634b624e0")]
            public virtual Ranorex.SpanTag Kleinteile_lager
            {
                get
                {
                    return _kleinteile_lagerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Kleinteile_lager item info.
            /// </summary>
            [RepositoryItemInfo("2d547e15-0327-462e-8765-583634b624e0")]
            public virtual RepoItemInfo Kleinteile_lagerInfo
            {
                get
                {
                    return _kleinteile_lagerInfo;
                }
            }

            /// <summary>
            /// The grossteile_lager item.
            /// </summary>
            [RepositoryItem("e8c65586-519a-4be7-95a7-4fa92d0cf2c1")]
            public virtual Ranorex.SpanTag grossteile_lager
            {
                get
                {
                    return _grossteile_lagerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The grossteile_lager item info.
            /// </summary>
            [RepositoryItemInfo("e8c65586-519a-4be7-95a7-4fa92d0cf2c1")]
            public virtual RepoItemInfo grossteile_lagerInfo
            {
                get
                {
                    return _grossteile_lagerInfo;
                }
            }

            /// <summary>
            /// The Ansprechpartner item.
            /// </summary>
            [RepositoryItem("1ad16f6b-2591-46a7-8c5f-77f1458c5ab6")]
            public virtual Ranorex.SpanTag Ansprechpartner
            {
                get
                {
                    return _ansprechpartnerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Ansprechpartner item info.
            /// </summary>
            [RepositoryItemInfo("1ad16f6b-2591-46a7-8c5f-77f1458c5ab6")]
            public virtual RepoItemInfo AnsprechpartnerInfo
            {
                get
                {
                    return _ansprechpartnerInfo;
                }
            }

            /// <summary>
            /// The Anfahrtsplan item.
            /// </summary>
            [RepositoryItem("c3213a13-836b-4ae6-a38d-e5af041caeec")]
            public virtual Ranorex.SpanTag Anfahrtsplan
            {
                get
                {
                    return _anfahrtsplanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Anfahrtsplan item info.
            /// </summary>
            [RepositoryItemInfo("c3213a13-836b-4ae6-a38d-e5af041caeec")]
            public virtual RepoItemInfo AnfahrtsplanInfo
            {
                get
                {
                    return _anfahrtsplanInfo;
                }
            }

            /// <summary>
            /// The Kontaktdaten item.
            /// </summary>
            [RepositoryItem("22b344e1-6d44-4634-b093-636330ef157a")]
            public virtual Ranorex.SpanTag Kontaktdaten
            {
                get
                {
                    return _kontaktdatenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Kontaktdaten item info.
            /// </summary>
            [RepositoryItemInfo("22b344e1-6d44-4634-b093-636330ef157a")]
            public virtual RepoItemInfo KontaktdatenInfo
            {
                get
                {
                    return _kontaktdatenInfo;
                }
            }
        }

        /// <summary>
        /// The PartnerBereichPageFolder folder.
        /// </summary>
        [RepositoryFolder("6397d9cb-9196-407e-9874-fbd641e3e292")]
        public partial class PartnerBereichPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logintextInfo;
            RepoItemInfo _benutzernameInfo;
            RepoItemInfo _passwortInfo;
            RepoItemInfo _anmeldenInfo;
            RepoItemInfo _angemeldet_bleibenInfo;
            RepoItemInfo _angemeldet_bleiben_checkboxInfo;
            RepoItemInfo _passwortvergessenInfo;
            RepoItemInfo _msg_supplyusernameandpasswordInfo;
            RepoItemInfo _msg_anerrorhasoccuredInfo;

            /// <summary>
            /// Creates a new PartnerBereichPage  folder.
            /// </summary>
            public PartnerBereichPageFolder(RepoGenBaseFolder parentFolder) :
                    base("PartnerBereichPage", "", parentFolder, 0, null, false, "6397d9cb-9196-407e-9874-fbd641e3e292", "")
            {
                _logintextInfo = new RepoItemInfo(this, "LoginText", ".//h2[@innertext='Bitte melden Sie sich hier an, um Zugriff auf den Partnerbereich zu bekommen:']", "element", 30000, null, "d2dda4c7-0fd7-4130-952a-5d623656ed60");
                _benutzernameInfo = new RepoItemInfo(this, "Benutzername", ".//input[@name='log']", "element", 30000, null, "91346a60-4c96-4469-b1cf-d5e2cbdf1d92");
                _passwortInfo = new RepoItemInfo(this, "Passwort", ".//input[@name='pwd']", "element", 30000, null, "f00f8474-be4a-49e3-8cb3-4a6c5037ecb0");
                _anmeldenInfo = new RepoItemInfo(this, "Anmelden", ".//input[@id='lwa_wp-submit']", "element", 30000, null, "bf746ff7-573a-4667-a9ae-793caa082d21");
                _angemeldet_bleibenInfo = new RepoItemInfo(this, "angemeldet_bleiben", ".//label[@innertext='angemeldet bleiben']", "element", 30000, null, "953fd775-40c4-46e1-8030-0e91def1b042");
                _angemeldet_bleiben_checkboxInfo = new RepoItemInfo(this, "angemeldet_bleiben_checkbox", ".//input[@name='rememberme']", "element", 30000, null, "49c0d6d2-322c-4b02-937a-70c1c84d0962");
                _passwortvergessenInfo = new RepoItemInfo(this, "PasswortVergessen", ".//a[@innertext='Passwort vergessen?']", "element", 30000, null, "3e61f14e-960b-46e1-9e04-27d8d9567343");
                _msg_supplyusernameandpasswordInfo = new RepoItemInfo(this, "Msg_SupplyUsernameAndPassword", ".//span[@innertext='Please supply your username and password.']", "element", 30000, null, "f28c94de-a2dd-4df8-a88e-b49a054410b0");
                _msg_anerrorhasoccuredInfo = new RepoItemInfo(this, "Msg_AnErrorHasOccured", ".//span[@innertext='An error has occured. Please try again.']", "element", 30000, null, "470bd538-a386-4cc4-99d3-ccc31aa020df");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6397d9cb-9196-407e-9874-fbd641e3e292")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginText item.
            /// </summary>
            [RepositoryItem("d2dda4c7-0fd7-4130-952a-5d623656ed60")]
            public virtual Ranorex.H2Tag LoginText
            {
                get
                {
                    return _logintextInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The LoginText item info.
            /// </summary>
            [RepositoryItemInfo("d2dda4c7-0fd7-4130-952a-5d623656ed60")]
            public virtual RepoItemInfo LoginTextInfo
            {
                get
                {
                    return _logintextInfo;
                }
            }

            /// <summary>
            /// The Benutzername item.
            /// </summary>
            [RepositoryItem("91346a60-4c96-4469-b1cf-d5e2cbdf1d92")]
            public virtual Ranorex.InputTag Benutzername
            {
                get
                {
                    return _benutzernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Benutzername item info.
            /// </summary>
            [RepositoryItemInfo("91346a60-4c96-4469-b1cf-d5e2cbdf1d92")]
            public virtual RepoItemInfo BenutzernameInfo
            {
                get
                {
                    return _benutzernameInfo;
                }
            }

            /// <summary>
            /// The Passwort item.
            /// </summary>
            [RepositoryItem("f00f8474-be4a-49e3-8cb3-4a6c5037ecb0")]
            public virtual Ranorex.InputTag Passwort
            {
                get
                {
                    return _passwortInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Passwort item info.
            /// </summary>
            [RepositoryItemInfo("f00f8474-be4a-49e3-8cb3-4a6c5037ecb0")]
            public virtual RepoItemInfo PasswortInfo
            {
                get
                {
                    return _passwortInfo;
                }
            }

            /// <summary>
            /// The Anmelden item.
            /// </summary>
            [RepositoryItem("bf746ff7-573a-4667-a9ae-793caa082d21")]
            public virtual Ranorex.InputTag Anmelden
            {
                get
                {
                    return _anmeldenInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Anmelden item info.
            /// </summary>
            [RepositoryItemInfo("bf746ff7-573a-4667-a9ae-793caa082d21")]
            public virtual RepoItemInfo AnmeldenInfo
            {
                get
                {
                    return _anmeldenInfo;
                }
            }

            /// <summary>
            /// The angemeldet_bleiben item.
            /// </summary>
            [RepositoryItem("953fd775-40c4-46e1-8030-0e91def1b042")]
            public virtual Ranorex.LabelTag angemeldet_bleiben
            {
                get
                {
                    return _angemeldet_bleibenInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The angemeldet_bleiben item info.
            /// </summary>
            [RepositoryItemInfo("953fd775-40c4-46e1-8030-0e91def1b042")]
            public virtual RepoItemInfo angemeldet_bleibenInfo
            {
                get
                {
                    return _angemeldet_bleibenInfo;
                }
            }

            /// <summary>
            /// The angemeldet_bleiben_checkbox item.
            /// </summary>
            [RepositoryItem("49c0d6d2-322c-4b02-937a-70c1c84d0962")]
            public virtual Ranorex.InputTag angemeldet_bleiben_checkbox
            {
                get
                {
                    return _angemeldet_bleiben_checkboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The angemeldet_bleiben_checkbox item info.
            /// </summary>
            [RepositoryItemInfo("49c0d6d2-322c-4b02-937a-70c1c84d0962")]
            public virtual RepoItemInfo angemeldet_bleiben_checkboxInfo
            {
                get
                {
                    return _angemeldet_bleiben_checkboxInfo;
                }
            }

            /// <summary>
            /// The PasswortVergessen item.
            /// </summary>
            [RepositoryItem("3e61f14e-960b-46e1-9e04-27d8d9567343")]
            public virtual Ranorex.ATag PasswortVergessen
            {
                get
                {
                    return _passwortvergessenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PasswortVergessen item info.
            /// </summary>
            [RepositoryItemInfo("3e61f14e-960b-46e1-9e04-27d8d9567343")]
            public virtual RepoItemInfo PasswortVergessenInfo
            {
                get
                {
                    return _passwortvergessenInfo;
                }
            }

            /// <summary>
            /// The Msg_SupplyUsernameAndPassword item.
            /// </summary>
            [RepositoryItem("f28c94de-a2dd-4df8-a88e-b49a054410b0")]
            public virtual Ranorex.SpanTag Msg_SupplyUsernameAndPassword
            {
                get
                {
                    return _msg_supplyusernameandpasswordInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Msg_SupplyUsernameAndPassword item info.
            /// </summary>
            [RepositoryItemInfo("f28c94de-a2dd-4df8-a88e-b49a054410b0")]
            public virtual RepoItemInfo Msg_SupplyUsernameAndPasswordInfo
            {
                get
                {
                    return _msg_supplyusernameandpasswordInfo;
                }
            }

            /// <summary>
            /// The Msg_AnErrorHasOccured item.
            /// </summary>
            [RepositoryItem("470bd538-a386-4cc4-99d3-ccc31aa020df")]
            public virtual Ranorex.SpanTag Msg_AnErrorHasOccured
            {
                get
                {
                    return _msg_anerrorhasoccuredInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Msg_AnErrorHasOccured item info.
            /// </summary>
            [RepositoryItemInfo("470bd538-a386-4cc4-99d3-ccc31aa020df")]
            public virtual RepoItemInfo Msg_AnErrorHasOccuredInfo
            {
                get
                {
                    return _msg_anerrorhasoccuredInfo;
                }
            }
        }

        /// <summary>
        /// The Pbs_shopSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("5d0c5407-5174-46d5-8a07-0ceee31a019a")]
        public partial class Pbs_shopSiteAppFolder : RepoGenBaseFolder
        {
            PBS_RepositoryFolders.HomePageFolder1 _homepage;
            PBS_RepositoryFolders.BuerobedarfPageFolder _buerobedarfpage;

            /// <summary>
            /// Creates a new pbs_shopSite  folder.
            /// </summary>
            public Pbs_shopSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("pbs_shopSite", "/dom[@domain='shop.pbs-austria.at']", parentFolder, 30000, null, false, "5d0c5407-5174-46d5-8a07-0ceee31a019a", "")
            {
                _homepage = new PBS_RepositoryFolders.HomePageFolder1(this);
                _buerobedarfpage = new PBS_RepositoryFolders.BuerobedarfPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5d0c5407-5174-46d5-8a07-0ceee31a019a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5d0c5407-5174-46d5-8a07-0ceee31a019a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("97da11b5-9c04-416c-8b75-d4c2e0bc9f4c")]
            public virtual PBS_RepositoryFolders.HomePageFolder1 HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The BuerobedarfPage folder.
            /// </summary>
            [RepositoryFolder("5c5642f8-59ca-41e2-bb1b-75c9fc2a468a")]
            public virtual PBS_RepositoryFolders.BuerobedarfPageFolder BuerobedarfPage
            {
                get { return _buerobedarfpage; }
            }
        }

        /// <summary>
        /// The HomePageFolder1 folder.
        /// </summary>
        [RepositoryFolder("97da11b5-9c04-416c-8b75-d4c2e0bc9f4c")]
        public partial class HomePageFolder1 : RepoGenBaseFolder
        {
            PBS_RepositoryFolders.HeaderFolder _header;
            RepoItemInfo _logoInfo;
            RepoItemInfo _searchbarInfo;
            RepoItemInfo _anmeldenInfo;
            RepoItemInfo _merklistenInfo;
            RepoItemInfo _vergleichInfo;
            RepoItemInfo _warenkorbInfo;
            RepoItemInfo _schreiben__malenInfo;
            RepoItemInfo _papier__hefteInfo;
            RepoItemInfo _buerobedarfInfo;
            RepoItemInfo _schulbedarfInfo;
            RepoItemInfo _mehrInfo;
            RepoItemInfo _carouselInfo;
            RepoItemInfo _neuheitenInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder1(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 0, null, false, "97da11b5-9c04-416c-8b75-d4c2e0bc9f4c", "")
            {
                _header = new PBS_RepositoryFolders.HeaderFolder(this);
                _logoInfo = new RepoItemInfo(this, "Logo", ".//img[@alt='Logo' and @visible='True']", "", 30000, null, "96b470c6-0a1c-49dd-bd37-9c480260f4c2");
                _searchbarInfo = new RepoItemInfo(this, "SearchBar", ".//form[#'SearchBox_Header']/input[@name='SearchTerm']", "element", 30000, null, "ec079832-5f94-4d79-a8a0-1f1fdaec403c");
                _anmeldenInfo = new RepoItemInfo(this, "Anmelden", ".//span[@innertext='Anmelden']", "element", 30000, null, "63922172-1d8e-48e2-ba8a-db9dad92b2f5");
                _merklistenInfo = new RepoItemInfo(this, "Merklisten", ".//span[@innertext='Merk­listen']", "element", 30000, null, "fe66fe24-915e-4193-8087-d803de7d55d0");
                _vergleichInfo = new RepoItemInfo(this, "Vergleich", ".//span[@innertext='Vergleich']", "element", 30000, null, "1df7bc67-2cfd-4738-8b83-91cfd996a52b");
                _warenkorbInfo = new RepoItemInfo(this, "Warenkorb", ".//span[@innertext='Waren­korb']", "element", 30000, null, "f9ccff64-6c5a-4fbb-a2fa-3fcdfedc87b6");
                _schreiben__malenInfo = new RepoItemInfo(this, "Schreiben__Malen", ".//a[@innertext='Schreiben & Malen']", "element", 30000, null, "b571aa16-7a08-4294-bfeb-0bb2e108b49d");
                _papier__hefteInfo = new RepoItemInfo(this, "Papier__Hefte", ".//a[@innertext='Papier & Hefte']", "element", 30000, null, "b3eeb7a4-0515-45f3-be0c-dcb750b4c9ad");
                _buerobedarfInfo = new RepoItemInfo(this, "Buerobedarf", ".//div[#'globalnav']//nav/ul//a[@innertext='Bürobedarf']", "element", 30000, null, "40ba5da4-42ef-4d97-a926-fb3fe95130fa");
                _schulbedarfInfo = new RepoItemInfo(this, "Schulbedarf", ".//a[@innertext='Schulbedarf']", "element", 30000, null, "ba588975-0a52-4b6f-b081-63549b5f4975");
                _mehrInfo = new RepoItemInfo(this, "Mehr", ".//span[@innertext=' Mehr ']", "element", 30000, null, "ccf2789f-1646-472e-8baa-61d7e3f54fff");
                _carouselInfo = new RepoItemInfo(this, "Carousel", ".//img[@class=' ls-is-cached lazyloaded' and @visible='True']", "", 30000, null, "9d7f7706-5d18-4e2e-861b-4a96f7076ec9");
                _neuheitenInfo = new RepoItemInfo(this, "Neuheiten", ".//h2[@innertext='Neuheiten']", "element", 30000, null, "1a39998f-e8b8-45ca-837a-a67acf857ca0");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97da11b5-9c04-416c-8b75-d4c2e0bc9f4c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logo item.
            /// </summary>
            [RepositoryItem("96b470c6-0a1c-49dd-bd37-9c480260f4c2")]
            public virtual Ranorex.ImgTag Logo
            {
                get
                {
                    return _logoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Logo item info.
            /// </summary>
            [RepositoryItemInfo("96b470c6-0a1c-49dd-bd37-9c480260f4c2")]
            public virtual RepoItemInfo LogoInfo
            {
                get
                {
                    return _logoInfo;
                }
            }

            /// <summary>
            /// The SearchBar item.
            /// </summary>
            [RepositoryItem("ec079832-5f94-4d79-a8a0-1f1fdaec403c")]
            public virtual Ranorex.InputTag SearchBar
            {
                get
                {
                    return _searchbarInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchBar item info.
            /// </summary>
            [RepositoryItemInfo("ec079832-5f94-4d79-a8a0-1f1fdaec403c")]
            public virtual RepoItemInfo SearchBarInfo
            {
                get
                {
                    return _searchbarInfo;
                }
            }

            /// <summary>
            /// The Anmelden item.
            /// </summary>
            [RepositoryItem("63922172-1d8e-48e2-ba8a-db9dad92b2f5")]
            public virtual Ranorex.SpanTag Anmelden
            {
                get
                {
                    return _anmeldenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Anmelden item info.
            /// </summary>
            [RepositoryItemInfo("63922172-1d8e-48e2-ba8a-db9dad92b2f5")]
            public virtual RepoItemInfo AnmeldenInfo
            {
                get
                {
                    return _anmeldenInfo;
                }
            }

            /// <summary>
            /// The Merklisten item.
            /// </summary>
            [RepositoryItem("fe66fe24-915e-4193-8087-d803de7d55d0")]
            public virtual Ranorex.SpanTag Merklisten
            {
                get
                {
                    return _merklistenInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Merklisten item info.
            /// </summary>
            [RepositoryItemInfo("fe66fe24-915e-4193-8087-d803de7d55d0")]
            public virtual RepoItemInfo MerklistenInfo
            {
                get
                {
                    return _merklistenInfo;
                }
            }

            /// <summary>
            /// The Vergleich item.
            /// </summary>
            [RepositoryItem("1df7bc67-2cfd-4738-8b83-91cfd996a52b")]
            public virtual Ranorex.SpanTag Vergleich
            {
                get
                {
                    return _vergleichInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Vergleich item info.
            /// </summary>
            [RepositoryItemInfo("1df7bc67-2cfd-4738-8b83-91cfd996a52b")]
            public virtual RepoItemInfo VergleichInfo
            {
                get
                {
                    return _vergleichInfo;
                }
            }

            /// <summary>
            /// The Warenkorb item.
            /// </summary>
            [RepositoryItem("f9ccff64-6c5a-4fbb-a2fa-3fcdfedc87b6")]
            public virtual Ranorex.SpanTag Warenkorb
            {
                get
                {
                    return _warenkorbInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Warenkorb item info.
            /// </summary>
            [RepositoryItemInfo("f9ccff64-6c5a-4fbb-a2fa-3fcdfedc87b6")]
            public virtual RepoItemInfo WarenkorbInfo
            {
                get
                {
                    return _warenkorbInfo;
                }
            }

            /// <summary>
            /// The Schreiben__Malen item.
            /// </summary>
            [RepositoryItem("b571aa16-7a08-4294-bfeb-0bb2e108b49d")]
            public virtual Ranorex.ATag Schreiben__Malen
            {
                get
                {
                    return _schreiben__malenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Schreiben__Malen item info.
            /// </summary>
            [RepositoryItemInfo("b571aa16-7a08-4294-bfeb-0bb2e108b49d")]
            public virtual RepoItemInfo Schreiben__MalenInfo
            {
                get
                {
                    return _schreiben__malenInfo;
                }
            }

            /// <summary>
            /// The Papier__Hefte item.
            /// </summary>
            [RepositoryItem("b3eeb7a4-0515-45f3-be0c-dcb750b4c9ad")]
            public virtual Ranorex.ATag Papier__Hefte
            {
                get
                {
                    return _papier__hefteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Papier__Hefte item info.
            /// </summary>
            [RepositoryItemInfo("b3eeb7a4-0515-45f3-be0c-dcb750b4c9ad")]
            public virtual RepoItemInfo Papier__HefteInfo
            {
                get
                {
                    return _papier__hefteInfo;
                }
            }

            /// <summary>
            /// The Buerobedarf item.
            /// </summary>
            [RepositoryItem("40ba5da4-42ef-4d97-a926-fb3fe95130fa")]
            public virtual Ranorex.ATag Buerobedarf
            {
                get
                {
                    return _buerobedarfInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Buerobedarf item info.
            /// </summary>
            [RepositoryItemInfo("40ba5da4-42ef-4d97-a926-fb3fe95130fa")]
            public virtual RepoItemInfo BuerobedarfInfo
            {
                get
                {
                    return _buerobedarfInfo;
                }
            }

            /// <summary>
            /// The Schulbedarf item.
            /// </summary>
            [RepositoryItem("ba588975-0a52-4b6f-b081-63549b5f4975")]
            public virtual Ranorex.ATag Schulbedarf
            {
                get
                {
                    return _schulbedarfInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Schulbedarf item info.
            /// </summary>
            [RepositoryItemInfo("ba588975-0a52-4b6f-b081-63549b5f4975")]
            public virtual RepoItemInfo SchulbedarfInfo
            {
                get
                {
                    return _schulbedarfInfo;
                }
            }

            /// <summary>
            /// The Mehr item.
            /// </summary>
            [RepositoryItem("ccf2789f-1646-472e-8baa-61d7e3f54fff")]
            public virtual Ranorex.SpanTag Mehr
            {
                get
                {
                    return _mehrInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Mehr item info.
            /// </summary>
            [RepositoryItemInfo("ccf2789f-1646-472e-8baa-61d7e3f54fff")]
            public virtual RepoItemInfo MehrInfo
            {
                get
                {
                    return _mehrInfo;
                }
            }

            /// <summary>
            /// The Carousel item.
            /// </summary>
            [RepositoryItem("9d7f7706-5d18-4e2e-861b-4a96f7076ec9")]
            public virtual Ranorex.ImgTag Carousel
            {
                get
                {
                    return _carouselInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Carousel item info.
            /// </summary>
            [RepositoryItemInfo("9d7f7706-5d18-4e2e-861b-4a96f7076ec9")]
            public virtual RepoItemInfo CarouselInfo
            {
                get
                {
                    return _carouselInfo;
                }
            }

            /// <summary>
            /// The Neuheiten item.
            /// </summary>
            [RepositoryItem("1a39998f-e8b8-45ca-837a-a67acf857ca0")]
            public virtual Ranorex.H2Tag Neuheiten
            {
                get
                {
                    return _neuheitenInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The Neuheiten item info.
            /// </summary>
            [RepositoryItemInfo("1a39998f-e8b8-45ca-837a-a67acf857ca0")]
            public virtual RepoItemInfo NeuheitenInfo
            {
                get
                {
                    return _neuheitenInfo;
                }
            }

            /// <summary>
            /// The Header folder.
            /// </summary>
            [RepositoryFolder("e0d125f6-3af5-4283-b849-1930c394a6bd")]
            public virtual PBS_RepositoryFolders.HeaderFolder Header
            {
                get { return _header; }
            }
        }

        /// <summary>
        /// The HeaderFolder folder.
        /// </summary>
        [RepositoryFolder("e0d125f6-3af5-4283-b849-1930c394a6bd")]
        public partial class HeaderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lieferungInfo;
            RepoItemInfo _riesige_auswahlInfo;
            RepoItemInfo _geschaeftskundenshopInfo;

            /// <summary>
            /// Creates a new Header  folder.
            /// </summary>
            public HeaderFolder(RepoGenBaseFolder parentFolder) :
                    base("Header", "", parentFolder, 0, null, false, "e0d125f6-3af5-4283-b849-1930c394a6bd", "")
            {
                _lieferungInfo = new RepoItemInfo(this, "Lieferung", ".//span[@innertext='Lieferung schnell & zuverlässig']", "element", 30000, null, "e37e6712-16ac-4518-bbf2-e284c17e82c6");
                _riesige_auswahlInfo = new RepoItemInfo(this, "riesige_Auswahl", ".//span[@innertext='riesige Auswahl']", "element", 30000, null, "2724b765-7aa7-4059-9a1a-e249003cb94f");
                _geschaeftskundenshopInfo = new RepoItemInfo(this, "Geschaeftskundenshop", ".//span[@innertext='Geschäftskundenshop. Alle Preise zzgl. USt.']", "element", 30000, null, "99fde26a-aff5-4975-b2af-fcf0a793ba61");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0d125f6-3af5-4283-b849-1930c394a6bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Lieferung item.
            /// </summary>
            [RepositoryItem("e37e6712-16ac-4518-bbf2-e284c17e82c6")]
            public virtual Ranorex.SpanTag Lieferung
            {
                get
                {
                    return _lieferungInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Lieferung item info.
            /// </summary>
            [RepositoryItemInfo("e37e6712-16ac-4518-bbf2-e284c17e82c6")]
            public virtual RepoItemInfo LieferungInfo
            {
                get
                {
                    return _lieferungInfo;
                }
            }

            /// <summary>
            /// The riesige_Auswahl item.
            /// </summary>
            [RepositoryItem("2724b765-7aa7-4059-9a1a-e249003cb94f")]
            public virtual Ranorex.SpanTag riesige_Auswahl
            {
                get
                {
                    return _riesige_auswahlInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The riesige_Auswahl item info.
            /// </summary>
            [RepositoryItemInfo("2724b765-7aa7-4059-9a1a-e249003cb94f")]
            public virtual RepoItemInfo riesige_AuswahlInfo
            {
                get
                {
                    return _riesige_auswahlInfo;
                }
            }

            /// <summary>
            /// The Geschaeftskundenshop item.
            /// </summary>
            [RepositoryItem("99fde26a-aff5-4975-b2af-fcf0a793ba61")]
            public virtual Ranorex.SpanTag Geschaeftskundenshop
            {
                get
                {
                    return _geschaeftskundenshopInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Geschaeftskundenshop item info.
            /// </summary>
            [RepositoryItemInfo("99fde26a-aff5-4975-b2af-fcf0a793ba61")]
            public virtual RepoItemInfo GeschaeftskundenshopInfo
            {
                get
                {
                    return _geschaeftskundenshopInfo;
                }
            }
        }

        /// <summary>
        /// The BuerobedarfPageFolder folder.
        /// </summary>
        [RepositoryFolder("5c5642f8-59ca-41e2-bb1b-75c9fc2a468a")]
        public partial class BuerobedarfPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buerobedarftextInfo;
            RepoItemInfo _buerobedarflabelInfo;
            RepoItemInfo _sortingInfo;
            RepoItemInfo _ansichtInfo;
            RepoItemInfo _kategorieInfo;
            RepoItemInfo _markeInfo;
            RepoItemInfo _umweltfreundlichInfo;
            RepoItemInfo _verfuegbarkeitInfo;
            RepoItemInfo _farbeInfo;
            RepoItemInfo _alle_filter_anzeigenInfo;
            RepoItemInfo _alle_filter_zuruecksetzenInfo;
            RepoItemInfo _vergleichslisteInfo;
            RepoItemInfo _numberofproductstocompareInfo;
            RepoItemInfo _product1Info;
            RepoItemInfo _product2Info;
            RepoItemInfo _chosenproduct1Info;
            RepoItemInfo _chosenproduct2Info;
            RepoItemInfo _filtercheckboxhpInfo;
            RepoItemInfo _productsInfo;

            /// <summary>
            /// Creates a new BuerobedarfPage  folder.
            /// </summary>
            public BuerobedarfPageFolder(RepoGenBaseFolder parentFolder) :
                    base("BuerobedarfPage", "", parentFolder, 0, null, false, "5c5642f8-59ca-41e2-bb1b-75c9fc2a468a", "")
            {
                _buerobedarftextInfo = new RepoItemInfo(this, "BuerobedarfText", ".//h1[@innertext='Bürobedarf']", "element", 30000, null, "036fe8ef-4fce-47b9-8daa-22e388d87064");
                _buerobedarflabelInfo = new RepoItemInfo(this, "BuerobedarfLabel", ".//div[#'product-search-result']//a[@innertext='Bürobedarf']", "element", 30000, null, "eb2d0190-4aef-4b96-93fb-8c6bb90e37e5");
                _sortingInfo = new RepoItemInfo(this, "Sorting", ".//select[#'SortingAttribute']", "element", 30000, null, "ab2315b3-4944-4104-824f-cb727fcf5e1c");
                _ansichtInfo = new RepoItemInfo(this, "Ansicht", ".//div[@innertext='Ansicht:']", "element", 30000, null, "84f163aa-0f78-4f2e-8dac-84b4f11fcac5");
                _kategorieInfo = new RepoItemInfo(this, "Kategorie", ".//div[#'category-accordion']/h3[@innertext='Kategorie']", "element", 30000, null, "a1d1455d-a159-4dca-93ae-fcbe0e03b1ce");
                _markeInfo = new RepoItemInfo(this, "Marke", ".//div[#'fg-Marke']//h3[@innertext='Marke']", "element", 30000, null, "63e3171a-1e2d-4b56-a421-4c93f982a438");
                _umweltfreundlichInfo = new RepoItemInfo(this, "Umweltfreundlich", ".//div[#'filter-accordion']//h3[@innertext>'Umweltfreundlich (ecommit']", "element", 30000, null, "630c503e-21a7-4b6d-9a27-728abeabc9c3");
                _verfuegbarkeitInfo = new RepoItemInfo(this, "Verfuegbarkeit", ".//div[#'fg-Verfügbarkeit']//h3[@innertext='Verfügbarkeit']", "element", 30000, null, "b9dc5191-c609-40fb-9cef-c57e306aecf8");
                _farbeInfo = new RepoItemInfo(this, "Farbe", ".//div[#'filter-accordion']//h3[@innertext='Farbe']", "element", 30000, null, "e893d18c-a423-4c16-9429-5ff4c22fb302");
                _alle_filter_anzeigenInfo = new RepoItemInfo(this, "Alle_Filter_anzeigen", ".//div[#'filter-accordion']/a[@innertext='Alle Filter anzeigen']", "element", 30000, null, "88a3033d-fb73-4681-836e-228bf1cc9157");
                _alle_filter_zuruecksetzenInfo = new RepoItemInfo(this, "Alle_Filter_zuruecksetzen", ".//div[#'filter-accordion']/a[@innertext='Alle Filter zurücksetzen']", "element", 30000, null, "27511aa7-d718-4d7f-b9fc-9f349b8a2e89");
                _vergleichslisteInfo = new RepoItemInfo(this, "Vergleichsliste", ".//span[@innertext='Vergleichsliste']", "element", 30000, null, "daa799fd-6d2c-45af-98e9-6585894be43a");
                _numberofproductstocompareInfo = new RepoItemInfo(this, "NumberOfProductsToCompare", ".//a[@title='Vergleich']//div[@innertext='2']", "element", 30000, null, "a76b2e2d-07f1-44d6-87fb-4ea717c2d64b");
                _product1Info = new RepoItemInfo(this, "Product1", ".//span[@innertext=$varProduct1]", "element", 30000, null, "a1d241e1-2ece-43aa-809f-2c024d17f4d8");
                _product2Info = new RepoItemInfo(this, "Product2", ".//span[@innertext=$varProduct2]", "element", 30000, null, "905c3008-bac6-4fcb-a843-0724f31d3f76");
                _chosenproduct1Info = new RepoItemInfo(this, "ChosenProduct1", ".//a[@innertext=$varChosenProduct1]", "element", 30000, null, "21290e16-79ca-4bb0-80fb-fe66f2dadedb");
                _chosenproduct2Info = new RepoItemInfo(this, "ChosenProduct2", ".//a[@innertext=$varChosenProduct2]", "element", 30000, null, "da60ca76-9566-4fca-9bfd-5e69290b2fa6");
                _filtercheckboxhpInfo = new RepoItemInfo(this, "FilterCheckboxHP", ".//ul[#'Marke_id']//input[@name='Manufacturer-HP']", "element", 30000, null, "18dcb31e-e94c-4f6c-b651-827e5086a56c");
                _productsInfo = new RepoItemInfo(this, "Products", ".//div[@class='product-tile ']", "element", 30000, null, "dc814f66-596a-474b-a3cf-d7e8e12ab6ac");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c5642f8-59ca-41e2-bb1b-75c9fc2a468a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BuerobedarfText item.
            /// </summary>
            [RepositoryItem("036fe8ef-4fce-47b9-8daa-22e388d87064")]
            public virtual Ranorex.H1Tag BuerobedarfText
            {
                get
                {
                    return _buerobedarftextInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The BuerobedarfText item info.
            /// </summary>
            [RepositoryItemInfo("036fe8ef-4fce-47b9-8daa-22e388d87064")]
            public virtual RepoItemInfo BuerobedarfTextInfo
            {
                get
                {
                    return _buerobedarftextInfo;
                }
            }

            /// <summary>
            /// The BuerobedarfLabel item.
            /// </summary>
            [RepositoryItem("eb2d0190-4aef-4b96-93fb-8c6bb90e37e5")]
            public virtual Ranorex.ATag BuerobedarfLabel
            {
                get
                {
                    return _buerobedarflabelInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BuerobedarfLabel item info.
            /// </summary>
            [RepositoryItemInfo("eb2d0190-4aef-4b96-93fb-8c6bb90e37e5")]
            public virtual RepoItemInfo BuerobedarfLabelInfo
            {
                get
                {
                    return _buerobedarflabelInfo;
                }
            }

            /// <summary>
            /// The Sorting item.
            /// </summary>
            [RepositoryItem("ab2315b3-4944-4104-824f-cb727fcf5e1c")]
            public virtual Ranorex.SelectTag Sorting
            {
                get
                {
                    return _sortingInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Sorting item info.
            /// </summary>
            [RepositoryItemInfo("ab2315b3-4944-4104-824f-cb727fcf5e1c")]
            public virtual RepoItemInfo SortingInfo
            {
                get
                {
                    return _sortingInfo;
                }
            }

            /// <summary>
            /// The Ansicht item.
            /// </summary>
            [RepositoryItem("84f163aa-0f78-4f2e-8dac-84b4f11fcac5")]
            public virtual Ranorex.DivTag Ansicht
            {
                get
                {
                    return _ansichtInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Ansicht item info.
            /// </summary>
            [RepositoryItemInfo("84f163aa-0f78-4f2e-8dac-84b4f11fcac5")]
            public virtual RepoItemInfo AnsichtInfo
            {
                get
                {
                    return _ansichtInfo;
                }
            }

            /// <summary>
            /// The Kategorie item.
            /// </summary>
            [RepositoryItem("a1d1455d-a159-4dca-93ae-fcbe0e03b1ce")]
            public virtual Ranorex.H3Tag Kategorie
            {
                get
                {
                    return _kategorieInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Kategorie item info.
            /// </summary>
            [RepositoryItemInfo("a1d1455d-a159-4dca-93ae-fcbe0e03b1ce")]
            public virtual RepoItemInfo KategorieInfo
            {
                get
                {
                    return _kategorieInfo;
                }
            }

            /// <summary>
            /// The Marke item.
            /// </summary>
            [RepositoryItem("63e3171a-1e2d-4b56-a421-4c93f982a438")]
            public virtual Ranorex.H3Tag Marke
            {
                get
                {
                    return _markeInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Marke item info.
            /// </summary>
            [RepositoryItemInfo("63e3171a-1e2d-4b56-a421-4c93f982a438")]
            public virtual RepoItemInfo MarkeInfo
            {
                get
                {
                    return _markeInfo;
                }
            }

            /// <summary>
            /// The Umweltfreundlich item.
            /// </summary>
            [RepositoryItem("630c503e-21a7-4b6d-9a27-728abeabc9c3")]
            public virtual Ranorex.H3Tag Umweltfreundlich
            {
                get
                {
                    return _umweltfreundlichInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Umweltfreundlich item info.
            /// </summary>
            [RepositoryItemInfo("630c503e-21a7-4b6d-9a27-728abeabc9c3")]
            public virtual RepoItemInfo UmweltfreundlichInfo
            {
                get
                {
                    return _umweltfreundlichInfo;
                }
            }

            /// <summary>
            /// The Verfuegbarkeit item.
            /// </summary>
            [RepositoryItem("b9dc5191-c609-40fb-9cef-c57e306aecf8")]
            public virtual Ranorex.H3Tag Verfuegbarkeit
            {
                get
                {
                    return _verfuegbarkeitInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Verfuegbarkeit item info.
            /// </summary>
            [RepositoryItemInfo("b9dc5191-c609-40fb-9cef-c57e306aecf8")]
            public virtual RepoItemInfo VerfuegbarkeitInfo
            {
                get
                {
                    return _verfuegbarkeitInfo;
                }
            }

            /// <summary>
            /// The Farbe item.
            /// </summary>
            [RepositoryItem("e893d18c-a423-4c16-9429-5ff4c22fb302")]
            public virtual Ranorex.H3Tag Farbe
            {
                get
                {
                    return _farbeInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The Farbe item info.
            /// </summary>
            [RepositoryItemInfo("e893d18c-a423-4c16-9429-5ff4c22fb302")]
            public virtual RepoItemInfo FarbeInfo
            {
                get
                {
                    return _farbeInfo;
                }
            }

            /// <summary>
            /// The Alle_Filter_anzeigen item.
            /// </summary>
            [RepositoryItem("88a3033d-fb73-4681-836e-228bf1cc9157")]
            public virtual Ranorex.ATag Alle_Filter_anzeigen
            {
                get
                {
                    return _alle_filter_anzeigenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Alle_Filter_anzeigen item info.
            /// </summary>
            [RepositoryItemInfo("88a3033d-fb73-4681-836e-228bf1cc9157")]
            public virtual RepoItemInfo Alle_Filter_anzeigenInfo
            {
                get
                {
                    return _alle_filter_anzeigenInfo;
                }
            }

            /// <summary>
            /// The Alle_Filter_zuruecksetzen item.
            /// </summary>
            [RepositoryItem("27511aa7-d718-4d7f-b9fc-9f349b8a2e89")]
            public virtual Ranorex.ATag Alle_Filter_zuruecksetzen
            {
                get
                {
                    return _alle_filter_zuruecksetzenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Alle_Filter_zuruecksetzen item info.
            /// </summary>
            [RepositoryItemInfo("27511aa7-d718-4d7f-b9fc-9f349b8a2e89")]
            public virtual RepoItemInfo Alle_Filter_zuruecksetzenInfo
            {
                get
                {
                    return _alle_filter_zuruecksetzenInfo;
                }
            }

            /// <summary>
            /// The Vergleichsliste item.
            /// </summary>
            [RepositoryItem("daa799fd-6d2c-45af-98e9-6585894be43a")]
            public virtual Ranorex.SpanTag Vergleichsliste
            {
                get
                {
                    return _vergleichslisteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Vergleichsliste item info.
            /// </summary>
            [RepositoryItemInfo("daa799fd-6d2c-45af-98e9-6585894be43a")]
            public virtual RepoItemInfo VergleichslisteInfo
            {
                get
                {
                    return _vergleichslisteInfo;
                }
            }

            /// <summary>
            /// The NumberOfProductsToCompare item.
            /// </summary>
            [RepositoryItem("a76b2e2d-07f1-44d6-87fb-4ea717c2d64b")]
            public virtual Ranorex.DivTag NumberOfProductsToCompare
            {
                get
                {
                    return _numberofproductstocompareInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NumberOfProductsToCompare item info.
            /// </summary>
            [RepositoryItemInfo("a76b2e2d-07f1-44d6-87fb-4ea717c2d64b")]
            public virtual RepoItemInfo NumberOfProductsToCompareInfo
            {
                get
                {
                    return _numberofproductstocompareInfo;
                }
            }

            /// <summary>
            /// The Product1 item.
            /// </summary>
            [RepositoryItem("a1d241e1-2ece-43aa-809f-2c024d17f4d8")]
            public virtual Ranorex.SpanTag Product1
            {
                get
                {
                    return _product1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Product1 item info.
            /// </summary>
            [RepositoryItemInfo("a1d241e1-2ece-43aa-809f-2c024d17f4d8")]
            public virtual RepoItemInfo Product1Info
            {
                get
                {
                    return _product1Info;
                }
            }

            /// <summary>
            /// The Product2 item.
            /// </summary>
            [RepositoryItem("905c3008-bac6-4fcb-a843-0724f31d3f76")]
            public virtual Ranorex.SpanTag Product2
            {
                get
                {
                    return _product2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Product2 item info.
            /// </summary>
            [RepositoryItemInfo("905c3008-bac6-4fcb-a843-0724f31d3f76")]
            public virtual RepoItemInfo Product2Info
            {
                get
                {
                    return _product2Info;
                }
            }

            /// <summary>
            /// The ChosenProduct1 item.
            /// </summary>
            [RepositoryItem("21290e16-79ca-4bb0-80fb-fe66f2dadedb")]
            public virtual Ranorex.ATag ChosenProduct1
            {
                get
                {
                    return _chosenproduct1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ChosenProduct1 item info.
            /// </summary>
            [RepositoryItemInfo("21290e16-79ca-4bb0-80fb-fe66f2dadedb")]
            public virtual RepoItemInfo ChosenProduct1Info
            {
                get
                {
                    return _chosenproduct1Info;
                }
            }

            /// <summary>
            /// The ChosenProduct2 item.
            /// </summary>
            [RepositoryItem("da60ca76-9566-4fca-9bfd-5e69290b2fa6")]
            public virtual Ranorex.ATag ChosenProduct2
            {
                get
                {
                    return _chosenproduct2Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ChosenProduct2 item info.
            /// </summary>
            [RepositoryItemInfo("da60ca76-9566-4fca-9bfd-5e69290b2fa6")]
            public virtual RepoItemInfo ChosenProduct2Info
            {
                get
                {
                    return _chosenproduct2Info;
                }
            }

            /// <summary>
            /// The FilterCheckboxHP item.
            /// </summary>
            [RepositoryItem("18dcb31e-e94c-4f6c-b651-827e5086a56c")]
            public virtual Ranorex.InputTag FilterCheckboxHP
            {
                get
                {
                    return _filtercheckboxhpInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FilterCheckboxHP item info.
            /// </summary>
            [RepositoryItemInfo("18dcb31e-e94c-4f6c-b651-827e5086a56c")]
            public virtual RepoItemInfo FilterCheckboxHPInfo
            {
                get
                {
                    return _filtercheckboxhpInfo;
                }
            }

            /// <summary>
            /// The Products item.
            /// </summary>
            [RepositoryItem("dc814f66-596a-474b-a3cf-d7e8e12ab6ac")]
            public virtual Ranorex.DivTag Products
            {
                get
                {
                    return _productsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Products item info.
            /// </summary>
            [RepositoryItemInfo("dc814f66-596a-474b-a3cf-d7e8e12ab6ac")]
            public virtual RepoItemInfo ProductsInfo
            {
                get
                {
                    return _productsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
