///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace pbs_web_automation.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HomePageValidation recording.
    /// </summary>
    [TestModule("2d2742fe-22bf-40fc-908a-96317dfe989b", ModuleType.Recording, 1)]
    public partial class HomePageValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::pbs_web_automation.PBS_Repository repository.
        /// </summary>
        public static global::pbs_web_automation.PBS_Repository repo = global::pbs_web_automation.PBS_Repository.Instance;

        static HomePageValidation instance = new HomePageValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HomePageValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HomePageValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Logo'.", repo.pbs_webSite.HomePage.LogoInfo, new RecordItemIndex(0));
            Validate.Exists(repo.pbs_webSite.HomePage.LogoInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Sortiment'.", repo.pbs_webSite.HomePage.SortimentInfo, new RecordItemIndex(1));
            Validate.Exists(repo.pbs_webSite.HomePage.SortimentInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Dienstleistungen'.", repo.pbs_webSite.HomePage.DienstleistungenInfo, new RecordItemIndex(2));
            Validate.Exists(repo.pbs_webSite.HomePage.DienstleistungenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Logistik'.", repo.pbs_webSite.HomePage.LogistikInfo, new RecordItemIndex(3));
            Validate.Exists(repo.pbs_webSite.HomePage.LogistikInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Kontakt'.", repo.pbs_webSite.HomePage.KontaktInfo, new RecordItemIndex(4));
            Validate.Exists(repo.pbs_webSite.HomePage.KontaktInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Fernwartung'.", repo.pbs_webSite.HomePage.FernwartungInfo, new RecordItemIndex(5));
            Validate.Exists(repo.pbs_webSite.HomePage.FernwartungInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Partnerbereich'.", repo.pbs_webSite.HomePage.PartnerbereichInfo, new RecordItemIndex(6));
            Validate.Exists(repo.pbs_webSite.HomePage.PartnerbereichInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.OnlineShop'.", repo.pbs_webSite.HomePage.OnlineShopInfo, new RecordItemIndex(7));
            Validate.Exists(repo.pbs_webSite.HomePage.OnlineShopInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Carousel'.", repo.pbs_webSite.HomePage.CarouselInfo, new RecordItemIndex(8));
            Validate.Exists(repo.pbs_webSite.HomePage.CarouselInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.PBS_Aktuell'.", repo.pbs_webSite.HomePage.PBS_AktuellInfo, new RecordItemIndex(9));
            Validate.Exists(repo.pbs_webSite.HomePage.PBS_AktuellInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
