///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace pbs_web_automation.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavbarValidation recording.
    /// </summary>
    [TestModule("c933cfdf-3186-41f3-a57f-ed4973d74765", ModuleType.Recording, 1)]
    public partial class NavbarValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::pbs_web_automation.PBS_Repository repository.
        /// </summary>
        public static global::pbs_web_automation.PBS_Repository repo = global::pbs_web_automation.PBS_Repository.Instance;

        static NavbarValidation instance = new NavbarValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavbarValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavbarValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Unternehmen
            Report.Log(ReportLevel.Info, "Section", "Unternehmen", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Unternehmen'.", repo.pbs_webSite.HomePage.UnternehmenInfo, new RecordItemIndex(1));
            Validate.Exists(repo.pbs_webSite.HomePage.UnternehmenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'pbs_webSite.HomePage.Unternehmen' at Center.", repo.pbs_webSite.HomePage.UnternehmenInfo, new RecordItemIndex(2));
            repo.pbs_webSite.HomePage.Unternehmen.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Unternehmensgruppe'.", repo.pbs_webSite.Navbar.UnternehmensgruppeInfo, new RecordItemIndex(3));
            Validate.Exists(repo.pbs_webSite.Navbar.UnternehmensgruppeInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.UberUns'.", repo.pbs_webSite.Navbar.UberUnsInfo, new RecordItemIndex(4));
            Validate.Exists(repo.pbs_webSite.Navbar.UberUnsInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Geschichte'.", repo.pbs_webSite.Navbar.GeschichteInfo, new RecordItemIndex(5));
            Validate.Exists(repo.pbs_webSite.Navbar.GeschichteInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Karriere'.", repo.pbs_webSite.Navbar.KarriereInfo, new RecordItemIndex(6));
            Validate.Exists(repo.pbs_webSite.Navbar.KarriereInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.DasTeam'.", repo.pbs_webSite.Navbar.DasTeamInfo, new RecordItemIndex(7));
            Validate.Exists(repo.pbs_webSite.Navbar.DasTeamInfo);
            Delay.Milliseconds(0);
            
            // Sortiment
            Report.Log(ReportLevel.Info, "Section", "Sortiment", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Sortiment'.", repo.pbs_webSite.HomePage.SortimentInfo, new RecordItemIndex(9));
            Validate.Exists(repo.pbs_webSite.HomePage.SortimentInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'pbs_webSite.HomePage.Sortiment' at Center.", repo.pbs_webSite.HomePage.SortimentInfo, new RecordItemIndex(10));
            repo.pbs_webSite.HomePage.Sortiment.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.UnserProduktangebot'.", repo.pbs_webSite.Navbar.UnserProduktangebotInfo, new RecordItemIndex(11));
            Validate.Exists(repo.pbs_webSite.Navbar.UnserProduktangebotInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Q_Connect'.", repo.pbs_webSite.Navbar.Q_ConnectInfo, new RecordItemIndex(12));
            Validate.Exists(repo.pbs_webSite.Navbar.Q_ConnectInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Donau'.", repo.pbs_webSite.Navbar.DonauInfo, new RecordItemIndex(13));
            Validate.Exists(repo.pbs_webSite.Navbar.DonauInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.E_Committed'.", repo.pbs_webSite.Navbar.E_CommittedInfo, new RecordItemIndex(14));
            Validate.Exists(repo.pbs_webSite.Navbar.E_CommittedInfo);
            Delay.Milliseconds(0);
            
            // Dienstleistungen
            Report.Log(ReportLevel.Info, "Section", "Dienstleistungen", new RecordItemIndex(15));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Dienstleistungen'.", repo.pbs_webSite.HomePage.DienstleistungenInfo, new RecordItemIndex(16));
            Validate.Exists(repo.pbs_webSite.HomePage.DienstleistungenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'pbs_webSite.HomePage.Dienstleistungen' at Center.", repo.pbs_webSite.HomePage.DienstleistungenInfo, new RecordItemIndex(17));
            repo.pbs_webSite.HomePage.Dienstleistungen.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.PersoenlicheBetreuung'.", repo.pbs_webSite.Navbar.PersoenlicheBetreuungInfo, new RecordItemIndex(18));
            Validate.Exists(repo.pbs_webSite.Navbar.PersoenlicheBetreuungInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Marketing_Service'.", repo.pbs_webSite.Navbar.Marketing_ServiceInfo, new RecordItemIndex(19));
            Validate.Exists(repo.pbs_webSite.Navbar.Marketing_ServiceInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Weiteres_Know_how'.", repo.pbs_webSite.Navbar.Weiteres_Know_howInfo, new RecordItemIndex(20));
            Validate.Exists(repo.pbs_webSite.Navbar.Weiteres_Know_howInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.CIPSCub_Systempartnerschaft'.", repo.pbs_webSite.Navbar.CIPSCub_SystempartnerschaftInfo, new RecordItemIndex(21));
            Validate.Exists(repo.pbs_webSite.Navbar.CIPSCub_SystempartnerschaftInfo);
            Delay.Milliseconds(0);
            
            // Logistik
            Report.Log(ReportLevel.Info, "Section", "Logistik", new RecordItemIndex(22));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Logistik'.", repo.pbs_webSite.HomePage.LogistikInfo, new RecordItemIndex(23));
            Validate.Exists(repo.pbs_webSite.HomePage.LogistikInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'pbs_webSite.HomePage.Logistik' at Center.", repo.pbs_webSite.HomePage.LogistikInfo, new RecordItemIndex(24));
            repo.pbs_webSite.HomePage.Logistik.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Logistikzentrum'.", repo.pbs_webSite.Navbar.LogistikzentrumInfo, new RecordItemIndex(25));
            Validate.Exists(repo.pbs_webSite.Navbar.LogistikzentrumInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.IT___PROZESSE'.", repo.pbs_webSite.Navbar.IT___PROZESSEInfo, new RecordItemIndex(26));
            Validate.Exists(repo.pbs_webSite.Navbar.IT___PROZESSEInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Kleinteile_lager'.", repo.pbs_webSite.Navbar.Kleinteile_lagerInfo, new RecordItemIndex(27));
            Validate.Exists(repo.pbs_webSite.Navbar.Kleinteile_lagerInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.grossteile_lager'.", repo.pbs_webSite.Navbar.grossteile_lagerInfo, new RecordItemIndex(28));
            Validate.Exists(repo.pbs_webSite.Navbar.grossteile_lagerInfo);
            Delay.Milliseconds(0);
            
            // Kontakt
            Report.Log(ReportLevel.Info, "Section", "Kontakt", new RecordItemIndex(29));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Kontakt'.", repo.pbs_webSite.HomePage.KontaktInfo, new RecordItemIndex(30));
            Validate.Exists(repo.pbs_webSite.HomePage.KontaktInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'pbs_webSite.HomePage.Kontakt' at Center.", repo.pbs_webSite.HomePage.KontaktInfo, new RecordItemIndex(31));
            repo.pbs_webSite.HomePage.Kontakt.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Ansprechpartner'.", repo.pbs_webSite.Navbar.AnsprechpartnerInfo, new RecordItemIndex(32));
            Validate.Exists(repo.pbs_webSite.Navbar.AnsprechpartnerInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Anfahrtsplan'.", repo.pbs_webSite.Navbar.AnfahrtsplanInfo, new RecordItemIndex(33));
            Validate.Exists(repo.pbs_webSite.Navbar.AnfahrtsplanInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.Navbar.Kontaktdaten'.", repo.pbs_webSite.Navbar.KontaktdatenInfo, new RecordItemIndex(34));
            Validate.Exists(repo.pbs_webSite.Navbar.KontaktdatenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Fernwartung'.", repo.pbs_webSite.HomePage.FernwartungInfo, new RecordItemIndex(35));
            Validate.Exists(repo.pbs_webSite.HomePage.FernwartungInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.HomePage.Partnerbereich'.", repo.pbs_webSite.HomePage.PartnerbereichInfo, new RecordItemIndex(36));
            Validate.Exists(repo.pbs_webSite.HomePage.PartnerbereichInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
