///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace pbs_web_automation.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PartnerbereichPageValidation recording.
    /// </summary>
    [TestModule("169da5b7-b01b-4ac8-a47d-984912a7e9a1", ModuleType.Recording, 1)]
    public partial class PartnerbereichPageValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::pbs_web_automation.PBS_Repository repository.
        /// </summary>
        public static global::pbs_web_automation.PBS_Repository repo = global::pbs_web_automation.PBS_Repository.Instance;

        static PartnerbereichPageValidation instance = new PartnerbereichPageValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PartnerbereichPageValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PartnerbereichPageValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.PartnerBereichPage.LoginText'.", repo.pbs_webSite.PartnerBereichPage.LoginTextInfo, new RecordItemIndex(0));
            Validate.Exists(repo.pbs_webSite.PartnerBereichPage.LoginTextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.PartnerBereichPage.Benutzername'.", repo.pbs_webSite.PartnerBereichPage.BenutzernameInfo, new RecordItemIndex(1));
            Validate.Exists(repo.pbs_webSite.PartnerBereichPage.BenutzernameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.PartnerBereichPage.Passwort'.", repo.pbs_webSite.PartnerBereichPage.PasswortInfo, new RecordItemIndex(2));
            Validate.Exists(repo.pbs_webSite.PartnerBereichPage.PasswortInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.PartnerBereichPage.Anmelden'.", repo.pbs_webSite.PartnerBereichPage.AnmeldenInfo, new RecordItemIndex(3));
            Validate.Exists(repo.pbs_webSite.PartnerBereichPage.AnmeldenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.PartnerBereichPage.angemeldet_bleiben'.", repo.pbs_webSite.PartnerBereichPage.angemeldet_bleibenInfo, new RecordItemIndex(4));
            Validate.Exists(repo.pbs_webSite.PartnerBereichPage.angemeldet_bleibenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.PartnerBereichPage.angemeldet_bleiben_checkbox'.", repo.pbs_webSite.PartnerBereichPage.angemeldet_bleiben_checkboxInfo, new RecordItemIndex(5));
            Validate.Exists(repo.pbs_webSite.PartnerBereichPage.angemeldet_bleiben_checkboxInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_webSite.PartnerBereichPage.PasswortVergessen'.", repo.pbs_webSite.PartnerBereichPage.PasswortVergessenInfo, new RecordItemIndex(6));
            Validate.Exists(repo.pbs_webSite.PartnerBereichPage.PasswortVergessenInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
