///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ShopSite.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChooseTwoProductsAndVerifyComparison recording.
    /// </summary>
    [TestModule("88ca03d9-58ce-42cd-9bd9-42772b352626", ModuleType.Recording, 1)]
    public partial class ChooseTwoProductsAndVerifyComparison : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::pbs_web_automation.PBS_Repository repository.
        /// </summary>
        public static global::pbs_web_automation.PBS_Repository repo = global::pbs_web_automation.PBS_Repository.Instance;

        static ChooseTwoProductsAndVerifyComparison instance = new ChooseTwoProductsAndVerifyComparison();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChooseTwoProductsAndVerifyComparison()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChooseTwoProductsAndVerifyComparison Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varProduct1.
        /// </summary>
        [TestVariable("b070db51-97f6-4cdd-a8b6-ca691242477b")]
        public string varProduct1
        {
            get { return repo.varProduct1; }
            set { repo.varProduct1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varProduct2.
        /// </summary>
        [TestVariable("d9e2e6aa-e4d2-4158-9d8f-01b927f841c1")]
        public string varProduct2
        {
            get { return repo.varProduct2; }
            set { repo.varProduct2 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varChosenProduct1.
        /// </summary>
        [TestVariable("0b84ec6a-3eed-4221-90ef-08943857ff01")]
        public string varChosenProduct1
        {
            get { return repo.varChosenProduct1; }
            set { repo.varChosenProduct1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varChosenProduct2.
        /// </summary>
        [TestVariable("efc2dd9e-6015-4679-8e6c-35d6c727ef50")]
        public string varChosenProduct2
        {
            get { return repo.varChosenProduct2; }
            set { repo.varChosenProduct2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(0));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'pbs_shopSite.BuerobedarfPage.Product1' at Center.", repo.pbs_shopSite.BuerobedarfPage.Product1Info, new RecordItemIndex(1));
            repo.pbs_shopSite.BuerobedarfPage.Product1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'pbs_shopSite.BuerobedarfPage.Vergleichsliste' at Center.", repo.pbs_shopSite.BuerobedarfPage.VergleichslisteInfo, new RecordItemIndex(2));
            repo.pbs_shopSite.BuerobedarfPage.Vergleichsliste.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'pbs_shopSite.HomePage.Buerobedarf' at Center.", repo.pbs_shopSite.HomePage.BuerobedarfInfo, new RecordItemIndex(4));
            repo.pbs_shopSite.HomePage.Buerobedarf.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'pbs_shopSite.BuerobedarfPage.Product2' at Center.", repo.pbs_shopSite.BuerobedarfPage.Product2Info, new RecordItemIndex(5));
            repo.pbs_shopSite.BuerobedarfPage.Product2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'pbs_shopSite.BuerobedarfPage.Vergleichsliste' at Center.", repo.pbs_shopSite.BuerobedarfPage.VergleichslisteInfo, new RecordItemIndex(6));
            repo.pbs_shopSite.BuerobedarfPage.Vergleichsliste.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'pbs_shopSite.BuerobedarfPage.NumberOfProductsToCompare'", repo.pbs_shopSite.BuerobedarfPage.NumberOfProductsToCompareInfo, new ActionTimeout(5000), new RecordItemIndex(7));
            repo.pbs_shopSite.BuerobedarfPage.NumberOfProductsToCompareInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'pbs_shopSite.HomePage.Vergleich' at Center.", repo.pbs_shopSite.HomePage.VergleichInfo, new RecordItemIndex(9));
            repo.pbs_shopSite.HomePage.Vergleich.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.BuerobedarfPage.ChosenProduct1'.", repo.pbs_shopSite.BuerobedarfPage.ChosenProduct1Info, new RecordItemIndex(11));
            Validate.Exists(repo.pbs_shopSite.BuerobedarfPage.ChosenProduct1Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.BuerobedarfPage.ChosenProduct2'.", repo.pbs_shopSite.BuerobedarfPage.ChosenProduct2Info, new RecordItemIndex(12));
            Validate.Exists(repo.pbs_shopSite.BuerobedarfPage.ChosenProduct2Info);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
