///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ShopSite.Recordings
{
    public partial class ControlFiltering
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CheckFilteredProducts()
        {
        	/*var repo = pbs_web_automation.PBS_Repository.Instance;
        	IList<Ranorex.Adapter> productTitles = repo.pbs_shopSite.BuerobedarfPage.ProductsInfo.CreateAdapters();*/
        	//var products = repo.pbs_shopSite.BuerobedarfPage.Products;
        	IList<Ranorex.Adapter> productTitles = Host.Local.Find<Ranorex.Adapter>("/dom[@domain='shop.pbs-austria.at']//div[@class='product-title']");

        	bool allContainHP = true;
        	foreach (var title in productTitles)
			{
    			string innerText = title.Element.GetAttributeValueText("InnerText");
    			if (!innerText.Contains("HP"))
    			{
        			allContainHP = false;
        			break;
    			}
			}

			if (allContainHP)
			{
    			Report.Success("All products contain 'HP'. Test Passed.");
			}
			else
			{
    		Report.Failure("Not all products contain 'HP'. Test Failed.");
			}

            
        }

    }
}
