///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ShopSite.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ShopHomePageValidation recording.
    /// </summary>
    [TestModule("9cf931d6-6418-4c38-a2ca-0c752126cc65", ModuleType.Recording, 1)]
    public partial class ShopHomePageValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::pbs_web_automation.PBS_Repository repository.
        /// </summary>
        public static global::pbs_web_automation.PBS_Repository repo = global::pbs_web_automation.PBS_Repository.Instance;

        static ShopHomePageValidation instance = new ShopHomePageValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ShopHomePageValidation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ShopHomePageValidation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Logo'.", repo.pbs_shopSite.HomePage.LogoInfo, new RecordItemIndex(0));
            Validate.Exists(repo.pbs_shopSite.HomePage.LogoInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.SearchBar'.", repo.pbs_shopSite.HomePage.SearchBarInfo, new RecordItemIndex(1));
            Validate.Exists(repo.pbs_shopSite.HomePage.SearchBarInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Header.Lieferung'.", repo.pbs_shopSite.HomePage.Header.LieferungInfo, new RecordItemIndex(2));
            Validate.Exists(repo.pbs_shopSite.HomePage.Header.LieferungInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Header.riesige_Auswahl'.", repo.pbs_shopSite.HomePage.Header.riesige_AuswahlInfo, new RecordItemIndex(3));
            Validate.Exists(repo.pbs_shopSite.HomePage.Header.riesige_AuswahlInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Header.Geschaeftskundenshop'.", repo.pbs_shopSite.HomePage.Header.GeschaeftskundenshopInfo, new RecordItemIndex(4));
            Validate.Exists(repo.pbs_shopSite.HomePage.Header.GeschaeftskundenshopInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Anmelden'.", repo.pbs_shopSite.HomePage.AnmeldenInfo, new RecordItemIndex(5));
            Validate.Exists(repo.pbs_shopSite.HomePage.AnmeldenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Merklisten'.", repo.pbs_shopSite.HomePage.MerklistenInfo, new RecordItemIndex(6));
            Validate.Exists(repo.pbs_shopSite.HomePage.MerklistenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Vergleich'.", repo.pbs_shopSite.HomePage.VergleichInfo, new RecordItemIndex(7));
            Validate.Exists(repo.pbs_shopSite.HomePage.VergleichInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Warenkorb'.", repo.pbs_shopSite.HomePage.WarenkorbInfo, new RecordItemIndex(8));
            Validate.Exists(repo.pbs_shopSite.HomePage.WarenkorbInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Schreiben__Malen'.", repo.pbs_shopSite.HomePage.Schreiben__MalenInfo, new RecordItemIndex(9));
            Validate.Exists(repo.pbs_shopSite.HomePage.Schreiben__MalenInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Papier__Hefte'.", repo.pbs_shopSite.HomePage.Papier__HefteInfo, new RecordItemIndex(10));
            Validate.Exists(repo.pbs_shopSite.HomePage.Papier__HefteInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Buerobedarf'.", repo.pbs_shopSite.HomePage.BuerobedarfInfo, new RecordItemIndex(11));
            Validate.Exists(repo.pbs_shopSite.HomePage.BuerobedarfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Schulbedarf'.", repo.pbs_shopSite.HomePage.SchulbedarfInfo, new RecordItemIndex(12));
            Validate.Exists(repo.pbs_shopSite.HomePage.SchulbedarfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Mehr'.", repo.pbs_shopSite.HomePage.MehrInfo, new RecordItemIndex(13));
            Validate.Exists(repo.pbs_shopSite.HomePage.MehrInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Carousel'.", repo.pbs_shopSite.HomePage.CarouselInfo, new RecordItemIndex(14));
            Validate.Exists(repo.pbs_shopSite.HomePage.CarouselInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'pbs_shopSite.HomePage.Neuheiten'.", repo.pbs_shopSite.HomePage.NeuheitenInfo, new RecordItemIndex(15));
            Validate.Exists(repo.pbs_shopSite.HomePage.NeuheitenInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
